### ISSUE TITLE
complete vg_1600_pre-trained_weights.pkl

### ISSUE THREAD

**Issue by TimmyWY2** [facebookresearch/video-long-term-feature-banks#14] opened 2019-07-15 10:52 UTC
vg_1600_pre-trained_weights.pkl does not have the final bbox predictions and classifications. Could you provide a complete model? thank you very much~

**Comment by chaoyuaw** [comment] 2019-07-17 00:05
Hi @TimmyWY2 , thanks for your question. Sure, please find the complete model at
https://drive.google.com/file/d/1FKksSY6URpzGtu0CFDLBpvkskzGpOD_e/view?usp=sharing

Just in case it's not clear in GETTING_STARTED.md, to reproduce our results the final bbox/classification layer shouldn't be needed, since we'll fine-tune it on EPIC-Kitchens. 

I'm closing this issue now, but please feel free to reopen if you have any questions! :) Thanks!

**Closed as completed by chaoyuaw** 2019-07-17 00:05 UTC
